@CityInfo.API_HostAddress = https://localhost:7132

POST {{CityInfo.API_HostAddress}}/api/authentication/authenticate
Content-Type: application/json

{
  //AuthenticationRequestBody
}

###

GET {{CityInfo.API_HostAddress}}/api/v{version:apiVersion}/cities?name=string&searchQuery=string

###

GET {{CityInfo.API_HostAddress}}/api/v{version:apiVersion}/cities/0/pointsofinterest

###

POST {{CityInfo.API_HostAddress}}/api/v{version:apiVersion}/cities/0/pointsofinterest
Content-Type: application/json

{
  //PointOfInterestForCreationDto
}

###
